server:
  port: 9190
spring:
  application:
      name: VEHICLERESTAPI
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle
    username: springboot
    password: springboot
    name: VehicleRestAPI
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:9194

