server:
  port: 9196
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: VEHICLE-SEARCH-API
#          uri: lb://VEHICLE-SEARCH-API
#          predicates:
#            - Path=/api/v1/vehicle-search/auth/**,/api/v1/vehicle-search/manufacturers/**,/api/v1/vehicle-search/model-trim/**,/api/v1/vehicle-search/vehicle-details/**,/api/v1/vehicle-search/vehicle-market-price/**
#          filters:
#            - AuthenticationFilter
#
#
#        - id: VEHICLE-DETAILS-API
#          uri: lb://VEHICLE-DETAILS-API
#          predicates:
#            - Path=/api/v1/vehicle-details/**
#          filters:
#            - AuthenticationFilter

