server:
  port: 9192
spring:
  application:
    name: VEHICLE-DETAILS-API
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle
    username: springboot
    password: springboot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:9194
