server:
  port: 9194
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/Emon-Khan/vehicle-rest-api-config
